"use strict";
const $=id=>document.getElementById(id), token=document.querySelector('meta[name="frictionlab-token"]').content;
let active=null,timer=null;
const categories=["functionality","usability","accessibility","responsiveness","performance","security"];
async function api(path,options={}){const response=await fetch(path,{...options,headers:{"Content-Type":"application/json","X-FrictionLab-Token":token,...options.headers}});if(!response.ok){const error=await response.json().catch(()=>({detail:"Local request failed"}));throw new Error(error.detail||"Request failed");}return response;}
const node=(tag,text,className)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;};
for(const category of categories){const label=node("label",undefined,"check"),input=node("input");input.type="checkbox";input.value=category;input.checked=true;label.append(input,node("span",category[0].toUpperCase()+category.slice(1)));$("categories").append(label);}
$("all").onclick=()=>document.querySelectorAll("#categories input").forEach(i=>i.checked=true);
function scope(){const mode=$("mode").value;$("upload-box").hidden=mode!=="snapshot";$("capture-box").hidden=mode!=="capture";$("scope").textContent={url_only:"Zero contact: no DNS lookup or website request. Most checks will be skipped until you supply an offline copy.",snapshot:"Zero target contact: only bundled HTML/CSS/images render at a synthetic origin. Website scripts, forms, frames and external requests are blocked. Dynamic flows cannot be tested from this copy.",capture:"One approved public GET, without authentication, redirects or subresources. Even a GET can change server state or logs. Upload a snapshot when zero contact is required."}[mode];}$("mode").onchange=scope;scope();
async function settings(){const value=await(await api("/api/settings")).json();$("connection").textContent=value.connected?`Connected: ${value.provider} / ${value.model}. Key value is never returned.`:"No AI connection. Structural checks work without a key.";$("remember").disabled=!value.secure_storage_available;if(value.provider!=="local"){$("provider").value=value.provider;$("model").value=value.model;providerScope();}}
function providerScope(){const morpheus=$("provider").value==="morpheus",fromEnv=morpheus&&$("local-env").checked;$("billing").disabled=!morpheus;$("free").disabled=morpheus;$("local-env").disabled=!morpheus;$("key").required=!fromEnv;$("key").disabled=fromEnv;$("remember").disabled=fromEnv;}$("provider").onchange=providerScope;$("local-env").onchange=providerScope;providerScope();
$("configure").onsubmit=async e=>{e.preventDefault();try{const body={provider:$("provider").value,key:$("key").value,model:$("model").value,remember:$("remember").checked&&!$("local-env").checked,share_findings:$("sharing").checked,free_tier_confirmed:$("free").checked,billing_acknowledged:$("billing").checked,use_local_env:$("local-env").checked};$("key").value="";await api("/api/settings",{method:"POST",body:JSON.stringify(body)});body.key="";$("key-status").textContent=body.use_local_env?"Connected using your ignored local .env key.":"Connected using process memory or native OS storage.";await settings();await agentReadiness();}catch(error){$("key").value="";$("key-status").textContent=error.message;}};
$("assessment").onsubmit=async e=>{e.preventDefault();$("error").textContent="";$("start").disabled=true;try{const body={url:$("url").value,categories:[...document.querySelectorAll("#categories input:checked")].map(i=>i.value),mode:$("mode").value,capture_authorized:$("capture-ok").checked,ai_enabled:$("ai").checked};if(!body.categories.length)throw new Error("Choose at least one category.");if(body.mode==="snapshot"){const file=$("snapshot").files[0];if(!file)throw new Error("Choose an HTML document or ZIP snapshot.");if(file.name.toLowerCase().endsWith(".zip")){if(file.size>10000000)throw new Error("ZIP exceeds 10 MB.");const bytes=new Uint8Array(await file.arrayBuffer());let binary="";for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));body.bundle_b64=btoa(binary);}else{if(file.size>2000000)throw new Error("HTML exceeds 2 MB.");body.html=await file.text();}}if(body.mode==="capture"&&!body.capture_authorized)throw new Error("Capture needs explicit permission and acknowledgement.");const result=await(await api("/api/assessments",{method:"POST",body:JSON.stringify(body)})).json();await follow(result.id);}catch(error){$("error").textContent=error.message;$("start").disabled=false;}};
async function follow(id){active=id;clearTimeout(timer);$("progress").hidden=false;$("results").hidden=true;$("cancel").disabled=false;$("start").disabled=true;await poll();}
async function poll(){try{const state=await(await api(`/api/assessments/${active}`)).json();$("stage").textContent=state.stage;$("bar").value=state.percent;$("progress-detail").textContent=`${state.status} · ${state.percent}%`;if(["queued","running"].includes(state.status)){timer=setTimeout(poll,1000);}else{$("cancel").disabled=true;$("start").disabled=false;show(await(await api(`/api/assessments/${active}/report`)).json());await loadHistory();}}catch(error){$("error").textContent=error.message;$("start").disabled=false;}}
$("cancel").onclick=async()=>{try{await api(`/api/assessments/${active}/cancel`,{method:"POST",body:"{}"});$("cancel").disabled=true;$("progress-detail").textContent="Cancellation requested. Bounded in-flight work will finish and retain a partial report.";}catch(error){$("error").textContent=error.message;}};
function show(report){$("results").hidden=false;$("scorecards").replaceChildren();const card=(title,score,description)=>{const el=node("div",undefined,"score");el.append(node("span",title),node("strong",score===null?"—":score),node("small",description));$("scorecards").append(el);};card("Overall",report.scores.overall,`Executed coverage ${report.scores.coverage}%`);for(const [cat,row]of Object.entries(report.scores.categories))card(cat,row.score,`Coverage ${row.coverage}% · Confidence ${row.confidence===null?"unassessed":row.confidence}`);$("issues").replaceChildren();if(!report.issues.length)$("issues").append(node("p","No issues found among executed checks. Review skipped/incomplete checks before drawing conclusions."));for(const issue of report.issues){const el=node("article",undefined,"issue");el.append(node("span",issue.severity,"badge"),node("h3",issue.title),node("p",issue.detail),node("p","Evidence: "+issue.evidence.join("; ")),node("p","Reproduce: "+issue.reproduction.join("; ")),node("p","Recommendation: "+issue.recommendation));if(issue.ai_recommendation)el.append(node("p","AI suggestion — review before applying: "+issue.ai_recommendation));$("issues").append(el);}$("check-table").replaceChildren(node("p",Object.entries(report.summary).map(([s,n])=>`${s}: ${n}`).join(" · ")));for(const check of report.checks){const el=node("div",undefined,"checkrow");el.append(node("strong",`${check.status.toUpperCase()} · ${check.category} · ${check.title}`),node("small",check.detail));$("check-table").append(el);}$("limitations").replaceChildren(node("p",report.scores.method),node("p","Acquisition: "+JSON.stringify(report.acquisition)),node("p","AI review: "+JSON.stringify(report.ai_review)));for(const text of report.limitations)$("limitations").append(node("p",text));$("exports").replaceChildren();for(const format of ["json","md","html","zip"]){const button=node("button",format.toUpperCase());button.onclick=async()=>{try{const blob=await(await api(`/api/assessments/${report.run_id}/export/${format}`)).blob(),url=URL.createObjectURL(blob),link=node("a");link.href=url;link.download=`frictionlab-${report.run_id}.${format}`;link.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}catch(error){$("error").textContent=error.message;}};$("exports").append(button);}}
async function loadHistory(){const runs=await(await api("/api/assessments")).json();$("history").replaceChildren();if(!runs.length)$("history").append(node("p","Your assessments will appear here and remain on this computer."));for(const run of runs){const button=node("button",`${run.id.slice(0,8)} · ${run.status}`);button.onclick=()=>follow(run.id);$("history").append(button);}}
const agentPanel=document.createElement("section");
agentPanel.className="card agent-panel";
agentPanel.innerHTML=`<span class="eyebrow">SYNTHETIC USER JOURNEY</span><h2>Run a browser agent on the bundled fixture</h2><p>This mode uses a disposable local storefront with synthetic data. It cannot test the website URL above. The selected AI model chooses bounded browser actions; model capability is verified by the run, not by a connection check.</p><p id="agent-ready" role="status">Checking agent readiness…</p><form id="agent-form"><div class="row"><div><label for="agent-persona">Persona</label><select id="agent-persona"><option value="impatient_mobile">Impatient mobile shopper</option><option value="keyboard_low_vision">Keyboard and low-vision user</option><option value="enterprise_evaluator">Enterprise evaluator</option></select></div><div><label for="agent-journey">Goal</label><select id="agent-journey"><option value="checkout_review">Review checkout</option><option value="delivery_information">Find delivery information</option><option value="keyboard_checkout">Complete keyboard checkout</option></select></div><div><label for="agent-variant">Fixture</label><select id="agent-variant"><option value="healthy">Healthy</option><option value="dead_button">Dead button</option><option value="generic_validation">Generic validation</option><option value="hidden_shipping">Hidden shipping</option><option value="delayed_feedback">Delayed feedback</option><option value="focus_trap">Focus trap</option></select></div></div><div class="row"><div><label for="agent-requests">Maximum AI requests</label><input id="agent-requests" type="number" min="1" max="12" value="8"></div><div><label for="agent-runtime">Maximum seconds</label><input id="agent-runtime" type="number" min="30" max="240" value="120"></div></div><label class="check"><input id="agent-usage" type="checkbox">I authorize this run's provider usage within these request and time limits; Morpheus may charge my account.</label><button id="agent-start" class="primary" type="submit">Start fixture agent →</button></form><p id="agent-error" role="alert"></p><div id="agent-progress" hidden><p id="agent-stage" role="status" aria-live="polite"></p><button id="agent-cancel" type="button">Stop agent</button></div><div id="agent-results" hidden></div><div id="agent-history"></div>`;
document.querySelector(".intro").after(agentPanel);
document.querySelector(".intro p").textContent="Run a synthetic browser agent on our disposable fixture, or assess an offline website copy. Review detailed local evidence and exports.";
let activeAgent=null,agentTimer=null;
async function agentReadiness(){const state=await(await api("/api/agents/readiness")).json();$("agent-ready").textContent=state.ready_to_attempt?`Ready to attempt a fixture journey with ${state.provider} / ${state.model}. Model action capability remains unverified until its first decision.`:state.gaps.join(" ");$("agent-start").disabled=!state.ready_to_attempt;}
$("agent-form").onsubmit=async e=>{e.preventDefault();$("agent-error").textContent="";$("agent-start").disabled=true;try{if(!$("agent-usage").checked)throw new Error("Authorize this run's bounded provider usage first.");const body={persona:$("agent-persona").value,journey:$("agent-journey").value,variant:$("agent-variant").value,max_requests:Number($("agent-requests").value),max_runtime_seconds:Number($("agent-runtime").value),account_usage_acknowledged:$("agent-usage").checked};const result=await(await api("/api/agents",{method:"POST",body:JSON.stringify(body)})).json();await followAgent(result.id);}catch(error){$("agent-error").textContent=error.message;await agentReadiness();}};
async function followAgent(id){activeAgent=id;clearTimeout(agentTimer);$("agent-progress").hidden=false;$("agent-results").hidden=true;await pollAgent();}
async function pollAgent(){try{const state=await(await api(`/api/agents/${activeAgent}`)).json();$("agent-stage").textContent=`${state.status} · ${state.stage}`;$("agent-cancel").disabled=!(["queued","running"].includes(state.status));if(["queued","running"].includes(state.status)){agentTimer=setTimeout(pollAgent,1000);}else{const report=await(await api(`/api/agents/${activeAgent}/report`)).json();showAgent(report);await agentReadiness();await agentHistory();}}catch(error){$("agent-error").textContent=error.message;}}
$("agent-cancel").onclick=async()=>{try{await api(`/api/agents/${activeAgent}/cancel`,{method:"POST",body:"{}"});$("agent-cancel").disabled=true;$("agent-stage").textContent="Stopping the bounded worker and saving partial evidence…";}catch(error){$("agent-error").textContent=error.message;}};
function showAgent(report){const results=$("agent-results");results.hidden=false;results.replaceChildren(node("h3","Agent report"),node("p",report.executive_summary),node("p",`Execution: ${report.execution_status}; report: ${report.report_status}. ${report.terminal_reason}`),node("p",`Model decisions: ${report.planner_decisions.length}; browser steps: ${report.trajectories.length}; friction events: ${report.friction_events.length}.`));if(report.abandonment_diagnosis)results.append(node("p",`Synthetic abandonment: ${report.abandonment_diagnosis.first_person}`));const limitations=node("div");limitations.append(node("h4","Limits and review"));for(const item of report.review.limitations)limitations.append(node("p",item));results.append(limitations);showAgentEvidence(report,results);for(const format of ["json","md","html","zip"]){const button=node("button",`Export ${format.toUpperCase()}`);button.onclick=async()=>{try{const blob=await(await api(`/api/agents/${report.run_id}/export/${format}`)).blob(),url=URL.createObjectURL(blob),link=node("a");link.href=url;link.download=`frictionlab-agent-${report.run_id}.${format}`;link.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}catch(error){$("agent-error").textContent=error.message;}};results.append(button);}}
async function agentHistory(){const runs=await(await api("/api/agents")).json();$("agent-history").replaceChildren(node("h3","Recent agent runs"));for(const run of runs){const button=node("button",`${run.id.slice(0,8)} · ${run.status}`);button.onclick=()=>followAgent(run.id);$("agent-history").append(button);}}
Promise.all([settings(),loadHistory(),agentReadiness(),agentHistory()]).catch(error=>$("error").textContent=error.message);
function showAgentEvidence(report,results){if(!report.visual_evidence.length)return;const gallery=node("div",undefined,"agent-evidence");gallery.append(node("h4","Saved screenshots"));for(const item of report.visual_evidence.slice(0,12)){const button=node("button",`View ${item.path}`);button.onclick=async()=>{try{const blob=await(await api(`/api/agents/${report.run_id}/evidence/${item.path}`)).blob(),url=URL.createObjectURL(blob),img=node("img");img.src=url;img.alt=`Saved agent screenshot ${item.path}`;img.onload=()=>URL.revokeObjectURL(url);gallery.append(img);}catch(error){$("agent-error").textContent=error.message;}};gallery.append(button);}results.append(gallery);}
