"use strict";
const $=id=>document.getElementById(id), token=document.querySelector('meta[name="frictionlab-token"]').content;
let active=null,timer=null;
const categories=["functionality","usability","accessibility","responsiveness","performance","security"];
async function api(path,options={}){const response=await fetch(path,{...options,headers:{"Content-Type":"application/json","X-FrictionLab-Token":token,...options.headers}});if(!response.ok){const error=await response.json().catch(()=>({detail:"Local request failed"}));throw new Error(error.detail||"Request failed");}return response;}
const node=(tag,text,className)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;};
for(const category of categories){const label=node("label",undefined,"check"),input=node("input");input.type="checkbox";input.value=category;input.checked=true;label.append(input,node("span",category[0].toUpperCase()+category.slice(1)));$("categories").append(label);}
$("all").onclick=()=>document.querySelectorAll("#categories input").forEach(i=>i.checked=true);
function scope(){const mode=$("mode").value;$("upload-box").hidden=mode!=="snapshot";$("capture-box").hidden=mode!=="capture";$("scope").textContent={url_only:"Zero contact: no DNS lookup or website request. Most checks will be skipped until you supply an offline copy.",snapshot:"Zero target contact: only bundled HTML/CSS/images render at a synthetic origin. Website scripts, forms, frames and external requests are blocked. Dynamic flows cannot be tested from this copy.",capture:"One approved public GET, without authentication, redirects or subresources. Even a GET can change server state or logs. Upload a snapshot when zero contact is required."}[mode];}$("mode").onchange=scope;scope();
async function settings(){const value=await(await api("/api/settings")).json();$("connection").textContent=value.connected?`Connected: ${value.provider} / ${value.model}. Key value is never returned.`:"No AI connection. Structural checks work without a key.";$("remember").disabled=!value.secure_storage_available;if(value.provider!=="local"){$("provider").value=value.provider;$("model").value=value.model;providerScope();}}
function providerScope(){const morpheus=$("provider").value==="morpheus",fromEnv=morpheus&&$("local-env").checked;$("billing").disabled=!morpheus;$("free").disabled=morpheus;$("local-env").disabled=!morpheus;$("key").required=!fromEnv;$("key").disabled=fromEnv;$("remember").disabled=fromEnv;}$("provider").onchange=providerScope;$("local-env").onchange=providerScope;providerScope();
$("configure").onsubmit=async e=>{e.preventDefault();try{const body={provider:$("provider").value,key:$("key").value,model:$("model").value,remember:$("remember").checked&&!$("local-env").checked,share_findings:$("sharing").checked,free_tier_confirmed:$("free").checked,billing_acknowledged:$("billing").checked,use_local_env:$("local-env").checked};$("key").value="";await api("/api/settings",{method:"POST",body:JSON.stringify(body)});body.key="";$("key-status").textContent=body.use_local_env?"Connected using your ignored local .env key.":"Connected using process memory or native OS storage.";await settings();}catch(error){$("key").value="";$("key-status").textContent=error.message;}};
$("assessment").onsubmit=async e=>{e.preventDefault();$("error").textContent="";$("start").disabled=true;try{const body={url:$("url").value,categories:[...document.querySelectorAll("#categories input:checked")].map(i=>i.value),mode:$("mode").value,capture_authorized:$("capture-ok").checked,ai_enabled:$("ai").checked};if(!body.categories.length)throw new Error("Choose at least one category.");if(body.mode==="snapshot"){const file=$("snapshot").files[0];if(!file)throw new Error("Choose an HTML document or ZIP snapshot.");if(file.name.toLowerCase().endsWith(".zip")){if(file.size>10000000)throw new Error("ZIP exceeds 10 MB.");const bytes=new Uint8Array(await file.arrayBuffer());let binary="";for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));body.bundle_b64=btoa(binary);}else{if(file.size>2000000)throw new Error("HTML exceeds 2 MB.");body.html=await file.text();}}if(body.mode==="capture"&&!body.capture_authorized)throw new Error("Capture needs explicit permission and acknowledgement.");const result=await(await api("/api/assessments",{method:"POST",body:JSON.stringify(body)})).json();await follow(result.id);}catch(error){$("error").textContent=error.message;$("start").disabled=false;}};
async function follow(id){active=id;clearTimeout(timer);$("progress").hidden=false;$("results").hidden=true;$("cancel").disabled=false;$("start").disabled=true;await poll();}
async function poll(){try{const state=await(await api(`/api/assessments/${active}`)).json();$("stage").textContent=state.stage;$("bar").value=state.percent;$("progress-detail").textContent=`${state.status} · ${state.percent}%`;if(["queued","running"].includes(state.status)){timer=setTimeout(poll,1000);}else{$("cancel").disabled=true;$("start").disabled=false;show(await(await api(`/api/assessments/${active}/report`)).json());await loadHistory();}}catch(error){$("error").textContent=error.message;$("start").disabled=false;}}
$("cancel").onclick=async()=>{try{await api(`/api/assessments/${active}/cancel`,{method:"POST",body:"{}"});$("cancel").disabled=true;$("progress-detail").textContent="Cancellation requested. Bounded in-flight work will finish and retain a partial report.";}catch(error){$("error").textContent=error.message;}};
function show(report){$("results").hidden=false;$("scorecards").replaceChildren();const card=(title,score,description)=>{const el=node("div",undefined,"score");el.append(node("span",title),node("strong",score===null?"—":score),node("small",description));$("scorecards").append(el);};card("Overall",report.scores.overall,`Executed coverage ${report.scores.coverage}%`);for(const [cat,row]of Object.entries(report.scores.categories))card(cat,row.score,`Coverage ${row.coverage}% · Confidence ${row.confidence===null?"unassessed":row.confidence}`);$("issues").replaceChildren();if(!report.issues.length)$("issues").append(node("p","No issues found among executed checks. Review skipped/incomplete checks before drawing conclusions."));for(const issue of report.issues){const el=node("article",undefined,"issue");el.append(node("span",issue.severity,"badge"),node("h3",issue.title),node("p",issue.detail),node("p","Evidence: "+issue.evidence.join("; ")),node("p","Reproduce: "+issue.reproduction.join("; ")),node("p","Recommendation: "+issue.recommendation));if(issue.ai_recommendation)el.append(node("p","AI suggestion — review before applying: "+issue.ai_recommendation));$("issues").append(el);}$("check-table").replaceChildren(node("p",Object.entries(report.summary).map(([s,n])=>`${s}: ${n}`).join(" · ")));for(const check of report.checks){const el=node("div",undefined,"checkrow");el.append(node("strong",`${check.status.toUpperCase()} · ${check.category} · ${check.title}`),node("small",check.detail));$("check-table").append(el);}$("limitations").replaceChildren(node("p",report.scores.method),node("p","Acquisition: "+JSON.stringify(report.acquisition)),node("p","AI review: "+JSON.stringify(report.ai_review)));for(const text of report.limitations)$("limitations").append(node("p",text));$("exports").replaceChildren();for(const format of ["json","md","html","zip"]){const button=node("button",format.toUpperCase());button.onclick=async()=>{try{const blob=await(await api(`/api/assessments/${report.run_id}/export/${format}`)).blob(),url=URL.createObjectURL(blob),link=node("a");link.href=url;link.download=`frictionlab-${report.run_id}.${format}`;link.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}catch(error){$("error").textContent=error.message;}};$("exports").append(button);}}
async function loadHistory(){const runs=await(await api("/api/assessments")).json();$("history").replaceChildren();if(!runs.length)$("history").append(node("p","Your assessments will appear here and remain on this computer."));for(const run of runs){const button=node("button",`${run.id.slice(0,8)} · ${run.status}`);button.onclick=()=>follow(run.id);$("history").append(button);}}
Promise.all([settings(),loadHistory()]).catch(error=>$("error").textContent=error.message);
